name: Build Aseprite Stable 1.3.14 (Windows x64)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build Aseprite 1.3.14 (Windows x64)
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          choco install -y ninja cmake python

      - name: Clone Aseprite (v1.3.14)
        run: |
          git clone --branch v1.3.14 --recursive https://github.com/aseprite/aseprite.git
          cd aseprite
          git submodule update --init --recursive

      - name: Add Spanish language support
        run: |
          cd aseprite/data
          curl -O https://raw.githubusercontent.com/aseprite/aseprite/v1.3.14/data/strings/es.ini
          cd ../..

      - name: Download Skia
        run: |
          mkdir skia
          curl -L https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-Windows-Release-x64.zip -o skia.zip
          7z x skia.zip -o./skia

      - name: Setup MSVC Developer Command Prompt
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - name: Build Aseprite
        run: |
          mkdir build
          cd build
          cmake ../aseprite -G Ninja ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DLAF_BACKEND=skia ^
            -DSKIA_DIR="${{ github.workspace }}/skia" ^
            -DSKIA_LIBRARY_DIR="${{ github.workspace }}/skia/out/Release-x64" ^
            -DSKIA_LIBRARY="${{ github.workspace }}/skia/out/Release-x64/skia.lib"
          ninja aseprite

      - name: Package artifacts
        run: |
          mkdir -p package
          cp build/bin/aseprite.exe package/
          cp build/bin/libcrypto-1_1-x64.dll package/
          cp -r aseprite/data package/
          7z a Aseprite-1.3.14-Windows-x64.zip ./package/*

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.3.14-custom
          name: "Aseprite 1.3.14 (Windows x64) with Spanish"
          body: "Custom build of Aseprite 1.3.14 with Spanish language support"
          files: |
            Aseprite-1.3.14-Windows-x64.zip
